Arithmetic
maksimsbogdanovs/c-sharp-basics pull request #5
Opened 2021-04-19 15:28 UTC by maksimsbogdanovs

Done!

2021-04-21 13:54 UTC, ausmoons requested changes
Pārej pāri failiem un sakārto

2021-04-21 13:54 UTC, ausmoons commented on .gitignore
> +*/**/obj/*
Atkal gitignore?

2021-04-21 13:54 UTC, ausmoons commented on Arithmetic/Exercise_9/Program.cs
> +                if (fbmi > 18.5 && fbmi < 25.0)
If else

2021-04-21 13:54 UTC, ausmoons commented on Arithmetic/Exercise_9/Program.cs
> +                if (fbmi > 18.5 && fbmi < 25.0)
Kas notiek ar 18.5 un 25.0?

2021-04-22 18:15 UTC, maksimsbogdanovs commented on .gitignore
> +*/**/obj/*
Laikam :( es pārgāju no Git Ext uz GitDesktop un kaut kas nojuka. Bet ceram ka nākamajiem viss būs ok.

2021-04-22 18:17 UTC, maksimsbogdanovs commented on Arithmetic/Exercise_9/Program.cs
> +                if (fbmi > 18.5 && fbmi < 25.0)
If else es lieku visiem, es pareizi saprotu? 

un ja ir no 18.5 līdz 25 tad viss ir ideāli, tu neesi ne underweight ne overweigth.:) Ja tas ir tas ko tu jautā.

2021-04-27 19:17 UTC, ausmoons requested changes

2021-04-27 19:17 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +
Kas te pa tukšajām rindām?

2021-04-27 19:17 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            // keyboard input
Izskatās pēc lieka komentāra

2021-04-27 19:17 UTC, ausmoons commented on Arithmetic/CozaLozaWoza/Program.cs
> +				{
While un pēc tam counter <=11?

2021-04-27 19:17 UTC, ausmoons commented on Arithmetic/Exercise_2/Program.cs
> +                keyInfo = Console.ReadKey();
Loops, kur vienkārši gaida enter?

2021-04-27 19:17 UTC, ausmoons commented on Arithmetic/Exercise_9/Program.cs
> +                else if (fbmi > 18.5 && fbmi < 25.0)
Kas notiek uz 18.5, 25.0 un 29.9?

2021-04-29 07:29 UTC, ausmoons requested changes
Gitignore un <=

2021-04-29 09:05 UTC, ausmoons approved these changes

2021-04-29 09:06 UTC, merged